import type { CommentItem, KanbanColumn } from '$lib/composables/useKanban'
import { assignees, tagPresets } from '$lib/composables/useKanban'

type AssigneeKey = keyof typeof assignees

function comment(id: string, who: AssigneeKey, text: string, time: string): CommentItem {
  return { id, author: assignees[who].name, authorColor: assignees[who].color, text, time }
}

export function createInitialColumns(): KanbanColumn[] {
  return [
    {
      id: 'backlog',
      title: 'Backlog',
      color: 'text-foreground',
      dotColor: 'bg-muted-foreground',
      tasks: [
        {
          id: 'APP-101',
          title: 'Write the migration guide for API v3',
          description: 'List breaking changes, add SDK code samples, review with developer relations',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [tagPresets.docs, tagPresets.release],
          dueDate: '2026-10-16',
          subtaskIds: ['APP-115', 'APP-116', 'APP-117'],
          commentItems: [
            comment('c1', 'bob', 'Should we include a section on pagination changes?', '2h ago'),
            comment('c2', 'alice', 'Yes, adding it. I\'m also checking how other APIs document cursor changes.', '1h ago'),
            comment('c3', 'david', 'Support asked for a before/after table for the webhook payloads.', '30m ago'),
          ],
          fileItems: [{ id: 'f1', name: 'API_v3_Breaking_Changes.pdf', size: '245 KB', type: 'pdf' }],
        },
        {
          id: 'APP-102',
          title: 'Evaluate feature-flag providers',
          priority: 'low',
          assignee: assignees.carol,
          tags: [tagPresets.infra],
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-103',
          title: 'Design empty states for the reports module',
          priority: 'medium',
          assignee: assignees.frank,
          tags: [tagPresets.design],
          dueDate: '2026-10-23',
          subtaskIds: [],
          commentItems: [
            comment('c1', 'alice', 'Can we reuse the illustrations from the projects page?', '1d ago'),
            comment('c2', 'frank', 'Mostly. Reports needs a "no data for this range" variant too.', '22h ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'Reports_Empty_States.xlsx', size: '128 KB', type: 'spreadsheet' },
            { id: 'f2', name: 'Empty_State_Mockups.png', size: '1.2 MB', type: 'image' },
            { id: 'f3', name: 'Copy_Review_Notes.pdf', size: '89 KB', type: 'pdf' },
          ],
        },
        {
          id: 'APP-116',
          title: 'Draft code samples for the SDK changes',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'APP-101',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-117',
          title: 'Review the guide with developer relations',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'APP-101',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'todo',
      title: 'To Do',
      color: 'text-foreground',
      dotColor: 'bg-info',
      tasks: [
        {
          id: 'APP-104',
          title: 'Onboard the Northwind Traders workspace',
          description: 'Kickoff call, data import and admin training for 40 seats',
          priority: 'high',
          assignee: assignees.bob,
          tags: [tagPresets.customer],
          dueDate: '2026-10-02',
          subtaskIds: [],
          commentItems: [
            comment('c1', 'alice', 'Their admin asked to move the kickoff to Thursday.', '3d ago'),
            comment('c2', 'bob', 'Updated. Thursday 2pm works for everyone.', '3d ago'),
            comment('c3', 'eva', 'The CSV import template is ready and shared in the account channel.', '2d ago'),
            comment('c4', 'bob', 'Thanks Eva. I\'ll walk them through it on the call.', '2d ago'),
            comment('c5', 'david', 'Can we include a short API walkthrough for their dev team?', '1d ago'),
            comment('c6', 'bob', 'Good call. Added a 30 min session after admin training.', '1d ago'),
            comment('c7', 'alice', 'All set. Let\'s sync after the kickoff.', '5h ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'Northwind_Onboarding_Plan.pdf', size: '156 KB', type: 'pdf' },
            { id: 'f2', name: 'Northwind_Seat_List.xlsx', size: '342 KB', type: 'spreadsheet' },
          ],
        },
        {
          id: 'APP-105',
          title: 'Fix webhook retries dropping events',
          priority: 'urgent',
          assignee: assignees.eva,
          tags: [tagPresets.bug],
          dueDate: '2026-09-26',
          subtaskIds: [],
          commentItems: [
            comment('c1', 'eva', 'Three workspaces reported missing invoice.paid events. Investigating.', '4h ago'),
          ],
          fileItems: [],
        },
        {
          id: 'APP-106',
          title: 'Update rate-limit docs for the Team plan',
          priority: 'medium',
          assignee: assignees.david,
          tags: [tagPresets.docs],
          subtaskIds: [],
          commentItems: [
            comment('c1', 'david', 'The limits table still shows the old 600 req/min figure.', '2d ago'),
            comment('c2', 'alice', 'Also document the burst allowance. Support gets asked about it weekly.', '2d ago'),
            comment('c3', 'frank', 'I can review the final draft before we publish.', '1d ago'),
            comment('c4', 'david', 'Thanks Frank. I\'ll have it ready by tomorrow.', '1d ago'),
          ],
          fileItems: [{ id: 'f1', name: 'Rate_Limits_Draft.pdf', size: '198 KB', type: 'pdf' }],
        },
        {
          id: 'APP-107',
          title: 'Add an SSO setup checklist to customer onboarding',
          priority: 'low',
          assignee: assignees.carol,
          tags: [tagPresets.customer, tagPresets.security],
          dueDate: '2026-10-09',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'in-progress',
      title: 'In Progress',
      color: 'text-foreground',
      dotColor: 'bg-warning',
      tasks: [
        {
          id: 'APP-108',
          title: 'Ship the v2.4 release with dashboard filters',
          description: 'Release branch, staging smoke tests, changelog and release notes',
          priority: 'high',
          assignee: assignees.alice,
          tags: [tagPresets.release],
          dueDate: '2026-10-01',
          subtaskIds: ['APP-118', 'APP-119', 'APP-120'],
          commentItems: [
            comment('c1', 'alice', 'Release branch is cut. Code freeze is in effect.', '3d ago'),
            comment('c2', 'frank', 'Staging deploy is green. Smoke tests are running now.', '3d ago'),
            comment('c3', 'bob', 'Filter presets look good on staging. One nit on the empty state copy.', '2d ago'),
            comment('c4', 'carol', 'Changelog draft is in the release doc.', '2d ago'),
            comment('c5', 'alice', 'One flaky test in the export suite. Looking into it.', '2d ago'),
            comment('c6', 'david', 'The flaky test was a timezone assumption. Fixed on the branch.', '1d ago'),
            comment('c7', 'eva', 'Load test on the new filter query: p95 is under 180 ms.', '1d ago'),
            comment('c8', 'frank', 'Feature flag is on for internal workspaces.', '20h ago'),
            comment('c9', 'alice', 'Great progress. Only release notes and the rollout are left.', '12h ago'),
            comment('c10', 'bob', 'Beta customers gave positive feedback on saved filters.', '8h ago'),
            comment('c11', 'carol', 'Release notes are two-thirds done.', '5h ago'),
            comment('c12', 'alice', 'Following up on the last section today.', '2h ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'v2.4_Release_Checklist.pdf', size: '312 KB', type: 'pdf' },
            { id: 'f2', name: 'Smoke_Test_Results.xlsx', size: '87 KB', type: 'spreadsheet' },
            { id: 'f3', name: 'Filters_Screenshot.png', size: '456 KB', type: 'image' },
            { id: 'f4', name: 'Rollout_Plan.pdf', size: '1.1 MB', type: 'pdf' },
            { id: 'f5', name: 'Release_Notes_Draft.pdf', size: '234 KB', type: 'pdf' },
          ],
        },
        {
          id: 'APP-109',
          title: 'Rotate API signing keys',
          priority: 'high',
          assignee: assignees.frank,
          tags: [tagPresets.security, tagPresets.infra],
          dueDate: '2026-10-06',
          subtaskIds: [],
          commentItems: [
            comment('c1', 'frank', 'New keys are generated and stored in the secrets manager.', '1d ago'),
            comment('c2', 'alice', 'Can we keep the old key valid for 7 days for slow clients?', '20h ago'),
            comment('c3', 'frank', 'Yes. Both keys are accepted until Oct 13.', '18h ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'Key_Rotation_Runbook.pdf', size: '2.4 MB', type: 'pdf' },
            { id: 'f2', name: 'Customer_Notice_Template.pdf', size: '67 KB', type: 'pdf' },
          ],
        },
        {
          id: 'APP-110',
          title: 'Redesign the billing settings page',
          priority: 'medium',
          assignee: assignees.david,
          tags: [tagPresets.design],
          subtaskIds: [],
          commentItems: [
            comment('c1', 'david', 'Starting from the current layout. Adding a usage section.', '3d ago'),
            comment('c2', 'bob', 'Can we show the next invoice date near the top?', '3d ago'),
            comment('c3', 'david', 'Good idea. Adding it with the payment method card.', '2d ago'),
            comment('c4', 'alice', 'Please share a preview first. The plan switcher confused people last time.', '1d ago'),
            comment('c5', 'david', 'Draft by Friday. The plan switcher is now a simple comparison list.', '1d ago'),
          ],
          fileItems: [{ id: 'f1', name: 'Billing_Settings_v3.pdf', size: '178 KB', type: 'pdf' }],
        },
        {
          id: 'APP-120',
          title: 'Publish the changelog and release notes',
          priority: 'medium',
          assignee: assignees.carol,
          tags: [],
          parentId: 'APP-108',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'in-review',
      title: 'In Review',
      color: 'text-foreground',
      dotColor: 'bg-chart-4',
      tasks: [
        {
          id: 'APP-111',
          title: 'Launch the usage-based pricing page',
          priority: 'high',
          assignee: assignees.bob,
          tags: [tagPresets.release],
          dueDate: '2026-09-30',
          subtaskIds: ['APP-121', 'APP-122', 'APP-123'],
          commentItems: [
            comment('c1', 'bob', 'All three plan cards are built. Sending to marketing for review.', '4d ago'),
            comment('c2', 'eva', 'Per-seat and per-call prices are confirmed. Updated the pricing sheet.', '4d ago'),
            comment('c3', 'david', 'The calculator rounds API calls oddly above 1M. Fixed.', '3d ago'),
            comment('c4', 'alice', 'Looks great overall. Let\'s get finance to sign off.', '3d ago'),
            comment('c5', 'bob', 'Finance review is submitted. ETA end of day Thursday.', '2d ago'),
            comment('c6', 'frank', 'Should we add annual pricing to each card?', '2d ago'),
            comment('c7', 'bob', 'Good point. Added an annual toggle.', '1d ago'),
            comment('c8', 'carol', 'The FAQ should explain what counts as an API call.', '1d ago'),
            comment('c9', 'bob', 'Done. The FAQ now has a usage section.', '6h ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'Pricing_Page_Spec.pdf', size: '892 KB', type: 'pdf' },
            { id: 'f2', name: 'Pricing_Model_Q4.xlsx', size: '234 KB', type: 'spreadsheet' },
            { id: 'f3', name: 'Launch_Timeline.pdf', size: '156 KB', type: 'pdf' },
            { id: 'f4', name: 'Pricing_Page_Mockup.png', size: '678 KB', type: 'image' },
          ],
        },
        {
          id: 'APP-112',
          title: 'Patch session timeouts on SSO logins',
          priority: 'urgent',
          assignee: assignees.eva,
          tags: [tagPresets.bug, tagPresets.security],
          dueDate: '2026-09-28',
          subtaskIds: [],
          commentItems: [
            comment('c1', 'eva', 'Found 12 workspaces where SSO sessions expire after 5 minutes.', '2d ago'),
            comment('c2', 'alice', 'Let\'s notify their admins while the fix is in review.', '2d ago'),
            comment('c3', 'eva', 'Notices sent. 8 admins have acknowledged so far.', '1d ago'),
            comment('c4', 'david', 'Does the fix need a token refresh for existing sessions?', '1d ago'),
            comment('c5', 'eva', 'Yes. It runs on next login, no forced sign-out.', '20h ago'),
            comment('c6', 'frank', 'Reviewed. Two small comments on the PR, otherwise good.', '6h ago'),
          ],
          fileItems: [{ id: 'f1', name: 'Affected_Workspaces.xlsx', size: '567 KB', type: 'spreadsheet' }],
        },
        {
          id: 'APP-123',
          title: 'Final pricing review with finance',
          priority: 'high',
          assignee: assignees.bob,
          tags: [],
          parentId: 'APP-111',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'done',
      title: 'Done',
      color: 'text-foreground',
      dotColor: 'bg-success',
      tasks: [
        {
          id: 'APP-113',
          title: 'Migrate background jobs to the new queue',
          priority: 'high',
          assignee: assignees.eva,
          tags: [tagPresets.infra],
          subtaskIds: [],
          commentItems: [
            comment('c1', 'eva', 'All job types are running on the new queue in staging.', '5d ago'),
            comment('c2', 'alice', 'Production cutover went through with no failed jobs.', '4d ago'),
            comment('c3', 'carol', 'Old workers are drained and removed.', '4d ago'),
            comment('c4', 'eva', 'Closing this out. Queue latency is down 40%.', '3d ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'Queue_Migration_Metrics.xlsx', size: '445 KB', type: 'spreadsheet' },
            { id: 'f2', name: 'Cutover_Runbook.pdf', size: '289 KB', type: 'pdf' },
          ],
        },
        {
          id: 'APP-114',
          title: 'Onboard Globex Corp from kickoff to go-live',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [tagPresets.customer],
          subtaskIds: ['APP-124', 'APP-125', 'APP-126'],
          commentItems: [
            comment('c1', 'alice', 'Kickoff deck sent. Their team starts Monday.', '3w ago'),
            comment('c2', 'bob', 'SSO is configured with their identity provider.', '3w ago'),
            comment('c3', 'carol', 'User provisioning is live for 120 seats.', '2w ago'),
            comment('c4', 'frank', 'Admin training done: roles, audit log and API keys.', '2w ago'),
            comment('c5', 'david', 'Historical data import finished with no errors.', '10d ago'),
            comment('c6', 'eva', 'First invoice is issued on the Team plan.', '9d ago'),
            comment('c7', 'alice', '30-day check-in done. Very positive feedback.', '2d ago'),
            comment('c8', 'alice', 'All tasks complete. Closing this onboarding ticket.', '1d ago'),
          ],
          fileItems: [
            { id: 'f1', name: 'Globex_Kickoff_Deck.pdf', size: '156 KB', type: 'pdf' },
            { id: 'f2', name: 'Globex_Project_Plan.pdf', size: '2.3 MB', type: 'pdf' },
            { id: 'f3', name: 'SSO_Config_Summary.pdf', size: '89 KB', type: 'pdf' },
            { id: 'f4', name: 'Admin_Training_Slides.pdf', size: '112 KB', type: 'pdf' },
            { id: 'f5', name: 'Seat_Provisioning.xlsx', size: '45 KB', type: 'spreadsheet' },
            { id: 'f6', name: '30Day_Check-in_Notes.pdf', size: '78 KB', type: 'pdf' },
          ],
        },
        {
          id: 'APP-115',
          title: 'Inventory breaking changes in the v3 endpoints',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'APP-101',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-118',
          title: 'Cut the release branch and freeze',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'APP-108',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-119',
          title: 'Run staging smoke tests',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'APP-108',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-121',
          title: 'Build the pricing calculator',
          priority: 'medium',
          assignee: assignees.bob,
          tags: [],
          parentId: 'APP-111',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-122',
          title: 'Write the plan comparison copy',
          priority: 'medium',
          assignee: assignees.bob,
          tags: [],
          parentId: 'APP-111',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-124',
          title: 'Send the kickoff deck and project plan',
          priority: 'low',
          assignee: assignees.alice,
          tags: [],
          parentId: 'APP-114',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-125',
          title: 'Configure SSO and user provisioning',
          priority: 'low',
          assignee: assignees.bob,
          tags: [],
          parentId: 'APP-114',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'APP-126',
          title: 'Import historical data',
          priority: 'low',
          assignee: assignees.carol,
          tags: [],
          parentId: 'APP-114',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
  ]
}
